services:  
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/home/app
    ports:
      - "4000:4000"
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: db
      PGPORT: 5432
    depends_on:
      - db
    network_mode: "host"

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  
volumes:
  app:
  pgdata:

networks:
  default:
