services:  
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    env_file:
      - shoe_phone.env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shoe_phone_database
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
  
volumes:
  app:
  pgdata:
    external: true

networks:
  default:
  